CREATE TABLE customers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  address VARCHAR(50),
  email VARCHAR(50) unique
);

CREATE TABLE products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(30),
  description VARCHAR(50),
  price INTEGER,
);

CREATE TABLE orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER references customers,
  order_date timestamp default 'now',
);

CREATE TABLE order_items (
  order_id INTEGER references orders
  product_id INTEGER references products,
  quantity integer,
);