
CREATE TABLE customers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(30),
  address VARCHAR(50),
  email VARCHAR(50) unique
);

CREATE TABLE products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(30) unique,
  description VARCHAR(10000),
  size VARCHAR(10),
  price INTEGER not null
);

CREATE TABLE orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER references customers not null,
  order_date timestamp
);

CREATE TABLE order_items (
  order_id INTEGER references orders not null,
  product_id INTEGER references products not null,
  quantity integer not null,
  PRIMARY KEY (order_id, product_id)
);

CREATE VIEW v_order_totals AS (
    SELECT o.id AS id, SUM(i.quantity * p.price) AS total_price
        FROM orders o join order_items i ON o.id = i.order_id
        JOIN products p on p.id = i.product_id GROUP BY o.id
);