CREATE TABLE customers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  address VARCHAR(50),
  email VARCHAR(50) unique
);

CREATE TABLE products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(30) unique,
  description VARCHAR(50),
  price INTEGER not null
);

CREATE TABLE orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER references customers not null,
  order_date timestamp
);

CREATE TABLE order_items (
  order_id INTEGER references orders not null,
  product_id INTEGER references products not null,
  quantity integer not null
);